{{- if .Values.server.sso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: argo-sso-secret
type: Opaque
stringData:
  clientId: {{ .Values.server.sso.clientId | default "" | quote  }}
  clientSecret: {{ .Values.server.sso.clientSecret | default "" | quote }}
{{- end }}
{{- if and .Values.server.enabled .Values.server.serviceAccount.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ template "argo-workflows.serverServiceAccountName" . }}
  name: {{ template "argo-workflows.serverServiceAccountName" . }}.service-account-token
  namespace: argo
type: kubernetes.io/service-account-token
{{- end }}
